package emit

import (
	"fmt"
	"strings"

	"github.com/danieljustus/symaira-desktop/internal/draw/scene"
)

// EmitTypst generates Typst markup representing the scene graph.
func EmitTypst(sc *scene.Scene) (string, error) {
	if sc == nil {
		return "", fmt.Errorf("scene is nil")
	}

	var sb strings.Builder
	sb.WriteString("// Generated by SymDraw\n")
	fmt.Fprintf(&sb, "#box(width: %spt, height: %spt, {\n", formatFloat(sc.Width), formatFloat(sc.Height))

	if sc.Background != "" && sc.Background != "none" && sc.Background != "transparent" {
		fmt.Fprintf(&sb, "  place(top + left, dx: 0pt, dy: 0pt, rect(width: 100%%, height: 100%%, fill: rgb(\"%s\")))\n", sc.Background)
	}

	for _, p := range sc.Primitives {
		switch el := p.(type) {
		case *scene.RectElement:
			fillStr := "none"
			if el.Fill != "" && el.Fill != "none" {
				fillStr = fmt.Sprintf("rgb(\"%s\")", el.Fill)
			}
			strokeStr := "none"
			if el.Stroke != "" && el.Stroke != "none" && el.StrokeWidth > 0 {
				strokeStr = fmt.Sprintf("%spt + rgb(\"%s\")", formatFloat(el.StrokeWidth), el.Stroke)
			}
			fmt.Fprintf(&sb, "  place(top + left, dx: %spt, dy: %spt, rect(width: %spt, height: %spt, radius: %spt, fill: %s, stroke: %s))\n",
				formatFloat(el.X), formatFloat(el.Y), formatFloat(el.Width), formatFloat(el.Height), formatFloat(el.Rx), fillStr, strokeStr)

		case *scene.CircleElement:
			fillStr := "none"
			if el.Fill != "" && el.Fill != "none" {
				fillStr = fmt.Sprintf("rgb(\"%s\")", el.Fill)
			}
			strokeStr := "none"
			if el.Stroke != "" && el.Stroke != "none" && el.StrokeWidth > 0 {
				strokeStr = fmt.Sprintf("%spt + rgb(\"%s\")", formatFloat(el.StrokeWidth), el.Stroke)
			}
			fmt.Fprintf(&sb, "  place(top + left, dx: %spt, dy: %spt, circle(radius: %spt, fill: %s, stroke: %s))\n",
				formatFloat(el.CX-el.R), formatFloat(el.CY-el.R), formatFloat(el.R), fillStr, strokeStr)

		case *scene.TextElement:
			fillStr := "black"
			if el.Fill != "" {
				fillStr = fmt.Sprintf("rgb(\"%s\")", el.Fill)
			}
			fontSize := el.FontSize
			if fontSize <= 0 {
				fontSize = 14
			}
			fmt.Fprintf(&sb, "  place(top + left, dx: %spt, dy: %spt, text(font: \"Inter\", size: %spt, fill: %s, [%s]))\n",
				formatFloat(el.X), formatFloat(el.Y-fontSize), formatFloat(fontSize), fillStr, escapeTypst(el.Text))
		}
	}

	sb.WriteString("})\n")
	return sb.String(), nil
}

func escapeTypst(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "[", "\\[")
	s = strings.ReplaceAll(s, "]", "\\]")
	s = strings.ReplaceAll(s, "$", "\\$")
	s = strings.ReplaceAll(s, "#", "\\#")
	return s
}
