package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/danieljustus/symaira-desktop/scripts/rust-port/inventory"
)

// These are declarative differential inputs and an immutable stdlib probe,
// not observations generated by the current full production source P. Roles
// are assigned to paths, never to a whitelist of acceptable commit hashes.
func isHistoricalFixture(rel string) bool {
	switch rel {
	case "testdata/port/cli/cases.json", "testdata/port/cli/retention-cases.json",
		"crates/symdesk-index/tests/data/dataset_sync_time/provenance.json":
		return true
	}
	return false
}

func descriptiveFixtureOracle(rel string) string {
	switch rel {
	case "testdata/port/vault/base-view-write.json":
		return "internal/dbviews.Manager file APIs"
	case "testdata/port/vault/notebook-write.json":
		return "internal/notebook (Go production API)"
	}
	return ""
}

// verifyFixtureIdentities reads only immutable Git objects. Every embedded
// source identity is either the canonical live P or a declared historical
// input/probe H whose existence and ancestry are checked separately.
func verifyFixtureIdentities(repoRoot, revision string, live inventory.Oracle) error {
	entries, err := gitOutput(repoRoot, "ls-tree", "-r", "-z", revision, "--", "testdata/port", "crates")
	if err != nil {
		return err
	}
	for _, entry := range bytes.Split(entries, []byte{0}) {
		if len(entry) == 0 {
			continue
		}
		header, rel, ok := strings.Cut(string(entry), "\t")
		if !ok || !strings.HasSuffix(rel, ".json") || (strings.HasPrefix(rel, "crates/") && !strings.Contains(rel, "/tests/data/")) {
			continue
		}
		if !strings.HasPrefix(header, "100644 blob ") {
			return fmt.Errorf("fixture identity input is not a regular 100644 blob: %s", rel)
		}
		content, err := gitOutput(repoRoot, "show", revision+":"+rel)
		if err != nil {
			return err
		}
		historical, err := validateFixtureIdentityDocument(rel, content, live)
		if err != nil {
			return fmt.Errorf("fixture identity %s: %w", rel, err)
		}
		for _, commit := range historical {
			if err := verifyProvenanceAncestryAt(repoRoot, revision, commit); err != nil {
				return fmt.Errorf("historical fixture identity %s: %w", rel, err)
			}
		}
		if rel == "crates/symdesk-index/tests/data/dataset_sync_time/provenance.json" {
			if err := verifyHistoricalProbe(repoRoot, revision, content); err != nil {
				return fmt.Errorf("historical time probe: %w", err)
			}
		}
	}
	return nil
}

func validateFixtureIdentityDocument(rel string, content []byte, live inventory.Oracle) ([]string, error) {
	if trimmed := bytes.TrimSpace(content); len(trimmed) != 0 && trimmed[0] == '[' {
		var rows []json.RawMessage
		if err := json.Unmarshal(content, &rows); err != nil {
			return nil, err
		}
		var historical []string
		for _, row := range rows {
			commits, err := validateFixtureIdentityDocument(rel, row, live)
			if err != nil {
				return nil, err
			}
			historical = append(historical, commits...)
		}
		return historical, nil
	}
	var document map[string]json.RawMessage
	if err := json.Unmarshal(content, &document); err != nil {
		return nil, fmt.Errorf("decode identity document: %w", err)
	}
	var commits []string
	var releases []string
	for _, name := range []string{"oracle_commit", "oracle_revision"} {
		if raw, ok := document[name]; ok {
			var commit string
			if err := json.Unmarshal(raw, &commit); err != nil {
				return nil, fmt.Errorf("%s must be a commit string", name)
			}
			commits = append(commits, commit)
		}
	}
	if raw, ok := document["oracle_release"]; ok {
		var release string
		if err := json.Unmarshal(raw, &release); err != nil {
			return nil, fmt.Errorf("oracle_release must be a string")
		}
		releases = append(releases, release)
	}
	if raw, ok := document["oracle"]; ok {
		var scalar string
		if json.Unmarshal(raw, &scalar) == nil {
			if scalar != descriptiveFixtureOracle(rel) || scalar == "" {
				commits = append(commits, scalar)
			}
		} else {
			var oracle struct {
				Commit  string  `json:"commit"`
				Release *string `json:"release"`
			}
			if err := json.Unmarshal(raw, &oracle); err != nil {
				return nil, fmt.Errorf("oracle must describe a source commit")
			}
			commits = append(commits, oracle.Commit)
			if oracle.Release != nil {
				releases = append(releases, *oracle.Release)
			}
		}
	}
	for _, commit := range commits {
		if !fullGitCommit.MatchString(commit) {
			return nil, fmt.Errorf("source identity must be a full lowercase commit: %q", commit)
		}
		if !isHistoricalFixture(rel) && commit != live.Commit {
			return nil, fmt.Errorf("live source identity differs from canonical P: got %s want %s", commit, live.Commit)
		}
	}
	for _, release := range releases {
		if strings.TrimSpace(release) == "" || (!isHistoricalFixture(rel) && release != live.Release) {
			return nil, fmt.Errorf("source release differs from its declared identity role: %q", release)
		}
	}
	if isHistoricalFixture(rel) {
		if len(commits) == 0 {
			return nil, fmt.Errorf("historical input/probe must retain its explicit H identity")
		}
		return commits, nil
	}
	return nil, nil
}

func verifyHistoricalProbe(repoRoot, revision string, content []byte) error {
	var probe struct {
		Commit       string `json:"oracle_revision"`
		SourcePath   string `json:"oracle_production_path"`
		SourceHash   string `json:"oracle_production_sha256"`
		ProbeHash    string `json:"time_probe_sha256"`
		RawHash      string `json:"time_raw_jsonl_sha256"`
		ObservedHash string `json:"time_observations_sha256"`
	}
	if err := json.Unmarshal(content, &probe); err != nil {
		return err
	}
	if !filepath.IsLocal(probe.SourcePath) || !strings.HasPrefix(probe.SourcePath, "internal/") || !strings.HasSuffix(probe.SourcePath, ".go") {
		return fmt.Errorf("invalid historical production source path")
	}
	const prefix = "crates/symdesk-index/tests/data/dataset_sync_time/"
	for _, input := range []struct{ revision, path, hash string }{
		{probe.Commit, probe.SourcePath, probe.SourceHash},
		{revision, prefix + "go_time_probe.go", probe.ProbeHash},
		{revision, prefix + "go_time_probe.jsonl", probe.RawHash},
		{revision, prefix + "go_time_observations.json", probe.ObservedHash},
	} {
		if !sha256LowerHex.MatchString(input.hash) {
			return fmt.Errorf("noncanonical historical probe hash for %s", input.path)
		}
		data, err := gitOutput(repoRoot, "show", input.revision+":"+input.path)
		if err != nil {
			return err
		}
		sum := sha256.Sum256(data)
		if hex.EncodeToString(sum[:]) != input.hash {
			return fmt.Errorf("historical source/probe bytes do not match recorded hash: %s", input.path)
		}
	}
	return nil
}
