#![deny(unsafe_code)]

//! Replays the Go-owned authoritative retention-state fixture generated by
//! `internal/service/port_retention_state_contract_test.go`.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use serde::Deserialize;
use symdesk_vault::{
    retention_state::{RetentionState, RetentionStateError, retention_state},
    sha256,
};

#[derive(Deserialize)]
struct Fixture {
    schema_version: u8,
    generated_on: String,
    oracle: Oracle,
    source_hashes: BTreeMap<String, String>,
    cases: Vec<Case>,
    mutations: Vec<Mutation>,
    notes: Vec<String>,
}

#[derive(Deserialize)]
struct Oracle {
    commit: String,
    release: String,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    description: String,
    path: String,
    #[serde(default)]
    setup: Vec<Setup>,
    state: Option<RetentionState>,
    #[serde(default)]
    error: String,
    #[serde(default)]
    error_class: String,
    platform: String,
}

#[derive(Deserialize)]
struct Mutation {
    id: String,
    description: String,
    path: String,
    setup: Vec<Setup>,
    mutation: Vec<Setup>,
    before: RetentionState,
    after: RetentionState,
    changed: bool,
    platform: String,
}

#[derive(Deserialize)]
struct Setup {
    path: String,
    kind: String,
    #[serde(default)]
    content: String,
    #[serde(default)]
    #[cfg_attr(not(unix), allow(dead_code))]
    target: String,
}

#[test]
fn retention_state_contracts_match_the_go_oracle() {
    let fixture = load_fixture();
    assert_eq!(fixture.schema_version, 1, "fixture schema version");
    assert_eq!(fixture.cases.len(), 14, "Go state case count");
    assert_eq!(fixture.mutations.len(), 2, "Go mutation case count");
    assert!(
        fixture.oracle.commit.len() == 40 && !fixture.oracle.release.is_empty(),
        "fixture must name the pinned Go oracle"
    );
    assert!(!fixture.generated_on.is_empty());
    assert!(!fixture.notes.is_empty());
    assert_source_hashes(&fixture);

    let mut observed = BTreeMap::new();
    let mut executed = 0usize;
    for case in &fixture.cases {
        if !platform_applies(&case.platform) {
            continue;
        }
        assert!(
            !case.description.is_empty(),
            "{} needs a description",
            case.id
        );
        if case.setup.iter().any(|entry| entry.kind == "fifo") {
            assert_special_file_case_bounded(case);
            executed += 1;
            continue;
        }
        let sandbox = Sandbox::new(&case.id);
        apply_setup(&sandbox, &case.setup);
        match retention_state(&sandbox.root, &case.path) {
            Ok(state) => {
                let expected = case
                    .state
                    .as_ref()
                    .unwrap_or_else(|| panic!("{} unexpectedly succeeded", case.id));
                assert_eq!(&state, expected, "{} state", case.id);
                assert!(case.error_class.is_empty(), "{} error class", case.id);
                observed.insert(case.id.as_str(), state.fingerprint.clone());
            }
            Err(error) => assert_case_error(case, &sandbox, &error),
        }
        executed += 1;
    }
    assert!(executed > 0, "no retention-state cases executed");
    assert_eq!(
        observed.get("dataset-sorted-raw-reverse-creation"),
        observed.get("dataset-sorted-raw-forward-creation"),
        "dataset raw-source ordering must be path-stable"
    );

    for mutation in &fixture.mutations {
        if !platform_applies(&mutation.platform) {
            continue;
        }
        assert!(
            !mutation.description.is_empty(),
            "{} needs a description",
            mutation.id
        );
        let sandbox = Sandbox::new(&mutation.id);
        apply_setup(&sandbox, &mutation.setup);
        let before = retention_state(&sandbox.root, &mutation.path)
            .unwrap_or_else(|error| panic!("{} before: {error}", mutation.id));
        assert_eq!(before, mutation.before, "{} before state", mutation.id);

        apply_setup(&sandbox, &mutation.mutation);
        let after = retention_state(&sandbox.root, &mutation.path)
            .unwrap_or_else(|error| panic!("{} after: {error}", mutation.id));
        assert_eq!(after, mutation.after, "{} after state", mutation.id);
        assert_eq!(
            before.fingerprint != after.fingerprint,
            mutation.changed,
            "{} fingerprint mutation verdict",
            mutation.id
        );
        assert!(
            mutation.changed,
            "{} must reject the staged fingerprint",
            mutation.id
        );
        executed += 1;
    }
    assert_eq!(
        executed,
        fixture
            .cases
            .iter()
            .filter(|case| platform_applies(&case.platform))
            .count()
            + fixture
                .mutations
                .iter()
                .filter(|case| platform_applies(&case.platform))
                .count(),
        "every applicable case executed"
    );
}

#[cfg(unix)]
fn assert_special_file_case_bounded(case: &Case) {
    use std::{
        fs::File,
        process::{Command, Stdio},
        thread,
        time::{Duration, Instant},
    };

    const CASE_ENV: &str = "SYMDESK_RETENTION_STATE_SPECIAL_FILE_CASE";
    const READY_ENV: &str = "SYMDESK_RETENTION_STATE_SPECIAL_FILE_READY";
    let run = Sandbox::new(&format!("bounded-{}", case.id));
    let ready = run.parent.join("entry.marker");
    let output_path = run.parent.join("child.log");
    let output = File::create(&output_path).expect("create special-file child log");
    let stderr = output.try_clone().expect("clone special-file child log");
    let mut child = Command::new(std::env::current_exe().expect("current test executable"))
        .args([
            "--exact",
            "retention_state_special_file_child",
            "--ignored",
            "--nocapture",
        ])
        .env(CASE_ENV, &case.id)
        .env(READY_ENV, &ready)
        .stdout(Stdio::from(output))
        .stderr(Stdio::from(stderr))
        .spawn()
        .unwrap_or_else(|error| panic!("{}: spawn bounded child: {error}", case.id));

    let startup_deadline = Instant::now() + Duration::from_secs(5);
    while !matches!(fs::read(&ready), Ok(marker) if marker == b"ENTRY\n") {
        if let Some(status) = child
            .try_wait()
            .unwrap_or_else(|error| panic!("{}: inspect bounded child: {error}", case.id))
        {
            let output = fs::read_to_string(&output_path).unwrap_or_default();
            panic!(
                "{}: child exited before ENTRY readiness with {status}:\n{output}",
                case.id
            );
        }
        if Instant::now() >= startup_deadline {
            let _ = child.kill();
            let _ = child.wait();
            let output = fs::read_to_string(&output_path).unwrap_or_default();
            panic!(
                "{}: child never reached ENTRY readiness:\n{output}",
                case.id
            );
        }
        thread::sleep(Duration::from_millis(5));
    }

    let completion_deadline = Instant::now() + Duration::from_secs(2);
    loop {
        if let Some(status) = child
            .try_wait()
            .unwrap_or_else(|error| panic!("{}: inspect bounded child: {error}", case.id))
        {
            let output = fs::read_to_string(&output_path).unwrap_or_default();
            assert!(
                status.success(),
                "{}: bounded child failed with {status}:\n{output}",
                case.id
            );
            return;
        }
        if Instant::now() >= completion_deadline {
            let _ = child.kill();
            let _ = child.wait();
            let output = fs::read_to_string(&output_path).unwrap_or_default();
            panic!(
                "{}: retention_state blocked for two seconds after ENTRY readiness:\n{output}",
                case.id
            );
        }
        thread::sleep(Duration::from_millis(5));
    }
}

#[cfg(not(unix))]
fn assert_special_file_case_bounded(case: &Case) {
    panic!(
        "Unix-only special-file case {} was not platform-filtered",
        case.id
    );
}

#[cfg(unix)]
#[test]
#[ignore = "child process body for bounded FIFO retention-state replay"]
fn retention_state_special_file_child() {
    const CASE_ENV: &str = "SYMDESK_RETENTION_STATE_SPECIAL_FILE_CASE";
    const READY_ENV: &str = "SYMDESK_RETENTION_STATE_SPECIAL_FILE_READY";
    let Ok(case_id) = std::env::var(CASE_ENV) else {
        return;
    };
    let ready = PathBuf::from(std::env::var_os(READY_ENV).expect("special-file readiness path"));
    let fixture = load_fixture();
    let case = fixture
        .cases
        .iter()
        .find(|case| case.id == case_id)
        .unwrap_or_else(|| panic!("missing special-file case {case_id}"));
    assert!(
        case.setup.iter().any(|entry| entry.kind == "fifo"),
        "{case_id} must create a FIFO"
    );
    let sandbox = Sandbox::new(&format!("child-{case_id}"));
    apply_setup(&sandbox, &case.setup);
    fs::write(&ready, b"ENTRY\n").expect("write special-file readiness");
    match retention_state(&sandbox.root, &case.path) {
        Ok(state) => panic!("{case_id} unexpectedly succeeded: {state:?}"),
        Err(error) => assert_case_error(case, &sandbox, &error),
    }
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/port/vault/retention-state.json")
}

fn load_fixture() -> Fixture {
    let path = fixture_path();
    let data = fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_slice(&data).expect("decode Go retention-state fixture")
}

fn assert_source_hashes(fixture: &Fixture) {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    for relative in [
        "internal/dataset/dataset.go",
        "internal/retention/fingerprint.go",
        "internal/retention/retention.go",
        "internal/service/dataset_retention.go",
        "internal/service/port_retention_state_contract_test.go",
        "internal/service/port_retention_state_unix_test.go",
        "internal/service/port_retention_state_windows_test.go",
        "internal/vault/root.go",
        "internal/vault/root_open_unix.go",
        "internal/vault/root_open_windows.go",
        "internal/vault/vault.go",
    ] {
        let expected = fixture
            .source_hashes
            .get(relative)
            .unwrap_or_else(|| panic!("missing source hash for {relative}"));
        let data = fs::read(root.join(relative))
            .unwrap_or_else(|error| panic!("read {relative}: {error}"));
        assert_eq!(sha256_hex(&data), *expected, "source hash for {relative}");
    }
}

fn assert_case_error(case: &Case, sandbox: &Sandbox, error: &RetentionStateError) {
    assert!(
        case.state.is_none(),
        "{} unexpectedly failed: {error}",
        case.id
    );
    assert_eq!(error.class(), case.error_class, "{} error class", case.id);
    let display_residual = match case.id.as_str() {
        "direct-fifo-rejected" => Some((
            "vault path is not a regular file: {{VAULT}}/pipe.md",
            "vault path is not a regular file: pipe.md",
        )),
        "dataset-raw-fifo-rejected" => Some((
            "vault path is not a regular file: {{VAULT}}/datasets/orders/pipe.csv",
            "vault path is not a regular file: datasets/orders/pipe.csv",
        )),
        _ => None,
    };
    if let Some((go_diagnostic, rust_diagnostic)) = display_residual {
        assert_eq!(case.error, go_diagnostic, "{} exact Go diagnostic", case.id);
        assert_eq!(
            error.to_string(),
            rust_diagnostic,
            "{} explicit Rust relative-path Display residual",
            case.id
        );
        return;
    }
    if !matches!(error.class(), "parse" | "filesystem" | "not_found") {
        assert_eq!(
            sanitise_error(&error.to_string(), sandbox),
            case.error,
            "{} error",
            case.id
        );
    }
}

fn platform_applies(platform: &str) -> bool {
    platform == "any" || (platform == "unix" && cfg!(unix))
}

fn apply_setup(sandbox: &Sandbox, entries: &[Setup]) {
    for entry in entries {
        let path = sandbox.root.join(Path::new(&entry.path));
        match entry.kind.as_str() {
            "directory" => fs::create_dir_all(&path).expect("create setup directory"),
            "file" => {
                fs::create_dir_all(path.parent().expect("setup file parent"))
                    .expect("create setup file parent");
                fs::write(&path, entry.content.as_bytes()).expect("write setup file");
            }
            "fifo" => create_fifo(&path),
            "symlink" => create_symlink(sandbox, entry, &path),
            other => panic!("unknown setup kind {other:?}"),
        }
    }
}

#[cfg(unix)]
fn create_fifo(path: &Path) {
    use std::process::Command;

    fs::create_dir_all(path.parent().expect("setup FIFO parent"))
        .expect("create setup FIFO parent");
    let binary = ["/usr/bin/mkfifo", "/bin/mkfifo"]
        .into_iter()
        .find(|candidate| Path::new(candidate).is_file())
        .unwrap_or("mkfifo");
    let status = Command::new(binary)
        .arg(path)
        .status()
        .unwrap_or_else(|error| panic!("run mkfifo for {}: {error}", path.display()));
    assert!(status.success(), "mkfifo failed for {}", path.display());
}

#[cfg(not(unix))]
fn create_fifo(path: &Path) {
    panic!(
        "Unix-only FIFO setup {} was not platform-filtered",
        path.display()
    );
}

#[cfg(unix)]
fn create_symlink(sandbox: &Sandbox, entry: &Setup, path: &Path) {
    use std::os::unix::fs::symlink;

    fs::create_dir_all(path.parent().expect("setup symlink parent"))
        .expect("create setup symlink parent");
    let _ = fs::remove_file(path);
    let target = if entry.target == "{{OUTSIDE_FILE}}" {
        sandbox.outside.clone()
    } else {
        PathBuf::from(&entry.target)
    };
    symlink(target, path).expect("create setup symlink");
}

#[cfg(not(unix))]
fn create_symlink(_sandbox: &Sandbox, _entry: &Setup, _path: &Path) {
    panic!("Unix-only symlink setup was not platform-filtered");
}

fn sanitise_error(message: &str, sandbox: &Sandbox) -> String {
    message
        .replace(&sandbox.root.to_string_lossy().to_string(), "{{VAULT}}")
        .replace(
            &sandbox.outside.to_string_lossy().to_string(),
            "{{OUTSIDE_FILE}}",
        )
        .replace('\\', "/")
}

fn sha256_hex(data: &[u8]) -> String {
    sha256::digest(data)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

static NEXT_SANDBOX: AtomicU64 = AtomicU64::new(0);

struct Sandbox {
    parent: PathBuf,
    root: PathBuf,
    outside: PathBuf,
}

impl Sandbox {
    fn new(label: &str) -> Self {
        let sequence = NEXT_SANDBOX.fetch_add(1, Ordering::Relaxed);
        let parent = std::env::temp_dir().join(format!(
            "symdesk-retention-state-{}-{sequence}-{label}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&parent);
        let root = parent.join("vault");
        fs::create_dir_all(&root).expect("create vault root");
        let outside = parent.join("outside.md");
        fs::write(&outside, b"outside\n").expect("write outside sentinel");
        Self {
            parent,
            root,
            outside,
        }
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.parent);
    }
}
