#![deny(unsafe_code)]

//! Replays the Go-owned authoritative retention-state fixture generated by
//! `internal/service/port_retention_state_contract_test.go`.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use serde::Deserialize;
use symdesk_vault::{
    retention_state::{RetentionState, RetentionStateError, retention_state},
    sha256,
};

#[derive(Deserialize)]
struct Fixture {
    schema_version: u8,
    generated_on: String,
    oracle: Oracle,
    source_hashes: BTreeMap<String, String>,
    cases: Vec<Case>,
    mutations: Vec<Mutation>,
    notes: Vec<String>,
}

#[derive(Deserialize)]
struct Oracle {
    commit: String,
    release: String,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    description: String,
    path: String,
    #[serde(default)]
    setup: Vec<Setup>,
    state: Option<RetentionState>,
    #[serde(default)]
    error: String,
    #[serde(default)]
    error_class: String,
    platform: String,
}

#[derive(Deserialize)]
struct Mutation {
    id: String,
    description: String,
    path: String,
    setup: Vec<Setup>,
    mutation: Vec<Setup>,
    before: RetentionState,
    after: RetentionState,
    changed: bool,
    platform: String,
}

#[derive(Deserialize)]
struct Setup {
    path: String,
    kind: String,
    #[serde(default)]
    content: String,
    #[serde(default)]
    target: String,
}

#[test]
fn retention_state_contracts_match_the_go_oracle() {
    let fixture = load_fixture();
    assert_eq!(fixture.schema_version, 1, "fixture schema version");
    assert_eq!(fixture.cases.len(), 11, "Go state case count");
    assert_eq!(fixture.mutations.len(), 2, "Go mutation case count");
    assert!(
        fixture.oracle.commit.len() == 40 && !fixture.oracle.release.is_empty(),
        "fixture must name the pinned Go oracle"
    );
    assert!(!fixture.generated_on.is_empty());
    assert!(!fixture.notes.is_empty());
    assert_source_hashes(&fixture);

    let mut observed = BTreeMap::new();
    let mut executed = 0usize;
    for case in &fixture.cases {
        if !platform_applies(&case.platform) {
            continue;
        }
        assert!(
            !case.description.is_empty(),
            "{} needs a description",
            case.id
        );
        let sandbox = Sandbox::new(&case.id);
        apply_setup(&sandbox, &case.setup);
        match retention_state(&sandbox.root, &case.path) {
            Ok(state) => {
                let expected = case
                    .state
                    .as_ref()
                    .unwrap_or_else(|| panic!("{} unexpectedly succeeded", case.id));
                assert_eq!(&state, expected, "{} state", case.id);
                assert!(case.error_class.is_empty(), "{} error class", case.id);
                observed.insert(case.id.as_str(), state.fingerprint.clone());
            }
            Err(error) => assert_case_error(case, &sandbox, &error),
        }
        executed += 1;
    }
    assert!(executed > 0, "no retention-state cases executed");
    assert_eq!(
        observed.get("dataset-sorted-raw-reverse-creation"),
        observed.get("dataset-sorted-raw-forward-creation"),
        "dataset raw-source ordering must be path-stable"
    );

    for mutation in &fixture.mutations {
        if !platform_applies(&mutation.platform) {
            continue;
        }
        assert!(
            !mutation.description.is_empty(),
            "{} needs a description",
            mutation.id
        );
        let sandbox = Sandbox::new(&mutation.id);
        apply_setup(&sandbox, &mutation.setup);
        let before = retention_state(&sandbox.root, &mutation.path)
            .unwrap_or_else(|error| panic!("{} before: {error}", mutation.id));
        assert_eq!(before, mutation.before, "{} before state", mutation.id);

        apply_setup(&sandbox, &mutation.mutation);
        let after = retention_state(&sandbox.root, &mutation.path)
            .unwrap_or_else(|error| panic!("{} after: {error}", mutation.id));
        assert_eq!(after, mutation.after, "{} after state", mutation.id);
        assert_eq!(
            before.fingerprint != after.fingerprint,
            mutation.changed,
            "{} fingerprint mutation verdict",
            mutation.id
        );
        assert!(
            mutation.changed,
            "{} must reject the staged fingerprint",
            mutation.id
        );
        executed += 1;
    }
    assert_eq!(
        executed,
        fixture
            .cases
            .iter()
            .filter(|case| platform_applies(&case.platform))
            .count()
            + fixture
                .mutations
                .iter()
                .filter(|case| platform_applies(&case.platform))
                .count(),
        "every applicable case executed"
    );
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/port/vault/retention-state.json")
}

fn load_fixture() -> Fixture {
    let path = fixture_path();
    let data = fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_slice(&data).expect("decode Go retention-state fixture")
}

fn assert_source_hashes(fixture: &Fixture) {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    for relative in [
        "internal/dataset/dataset.go",
        "internal/retention/fingerprint.go",
        "internal/retention/retention.go",
        "internal/service/dataset_retention.go",
        "internal/service/port_retention_state_contract_test.go",
        "internal/vault/root.go",
        "internal/vault/vault.go",
    ] {
        let expected = fixture
            .source_hashes
            .get(relative)
            .unwrap_or_else(|| panic!("missing source hash for {relative}"));
        let data = fs::read(root.join(relative))
            .unwrap_or_else(|error| panic!("read {relative}: {error}"));
        assert_eq!(sha256_hex(&data), *expected, "source hash for {relative}");
    }
}

fn assert_case_error(case: &Case, sandbox: &Sandbox, error: &RetentionStateError) {
    assert!(
        case.state.is_none(),
        "{} unexpectedly failed: {error}",
        case.id
    );
    assert_eq!(error.class(), case.error_class, "{} error class", case.id);
    if !matches!(error.class(), "parse" | "filesystem" | "not_found") {
        assert_eq!(
            sanitise_error(&error.to_string(), sandbox),
            case.error,
            "{} error",
            case.id
        );
    }
}

fn platform_applies(platform: &str) -> bool {
    platform == "any" || (platform == "unix" && cfg!(unix))
}

fn apply_setup(sandbox: &Sandbox, entries: &[Setup]) {
    for entry in entries {
        let path = sandbox.root.join(Path::new(&entry.path));
        match entry.kind.as_str() {
            "directory" => fs::create_dir_all(&path).expect("create setup directory"),
            "file" => {
                fs::create_dir_all(path.parent().expect("setup file parent"))
                    .expect("create setup file parent");
                fs::write(&path, entry.content.as_bytes()).expect("write setup file");
            }
            "symlink" => create_symlink(sandbox, entry, &path),
            other => panic!("unknown setup kind {other:?}"),
        }
    }
}

#[cfg(unix)]
fn create_symlink(sandbox: &Sandbox, entry: &Setup, path: &Path) {
    use std::os::unix::fs::symlink;

    fs::create_dir_all(path.parent().expect("setup symlink parent"))
        .expect("create setup symlink parent");
    let _ = fs::remove_file(path);
    let target = if entry.target == "{{OUTSIDE_FILE}}" {
        sandbox.outside.clone()
    } else {
        PathBuf::from(&entry.target)
    };
    symlink(target, path).expect("create setup symlink");
}

#[cfg(not(unix))]
fn create_symlink(_sandbox: &Sandbox, _entry: &Setup, _path: &Path) {
    panic!("Unix-only symlink setup was not platform-filtered");
}

fn sanitise_error(message: &str, sandbox: &Sandbox) -> String {
    message
        .replace(&sandbox.root.to_string_lossy().to_string(), "{{VAULT}}")
        .replace(
            &sandbox.outside.to_string_lossy().to_string(),
            "{{OUTSIDE_FILE}}",
        )
        .replace('\\', "/")
}

fn sha256_hex(data: &[u8]) -> String {
    sha256::digest(data)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

static NEXT_SANDBOX: AtomicU64 = AtomicU64::new(0);

struct Sandbox {
    parent: PathBuf,
    root: PathBuf,
    outside: PathBuf,
}

impl Sandbox {
    fn new(label: &str) -> Self {
        let sequence = NEXT_SANDBOX.fetch_add(1, Ordering::Relaxed);
        let parent = std::env::temp_dir().join(format!(
            "symdesk-retention-state-{}-{sequence}-{label}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&parent);
        let root = parent.join("vault");
        fs::create_dir_all(&root).expect("create vault root");
        let outside = parent.join("outside.md");
        fs::write(&outside, b"outside\n").expect("write outside sentinel");
        Self {
            parent,
            root,
            outside,
        }
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.parent);
    }
}
