package retention

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/danieljustus/symaira-desktop/internal/vault"
)

const (
	retentionRulesFixturePath = "testdata/port/vault/retention-rules.json"
	schemaVersion             = 1
	sourceOracleCommit        = "745c08e8b9d1b1a9cbb2e0ba1c1d0d0d5c0f0f7a"
	sourceOracleRelease       = "v0.1.0"
)

type RetentionOracle struct {
	Commit  string `json:"commit"`
	Release string `json:"release"`
}

type loadRulesVector struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	YAMLContent string `json:"yaml_content"`
	Rules       []Rule `json:"rules,omitempty"`
	Error       string `json:"error,omitempty"`
	ErrorClass  string `json:"error_class,omitempty"`
}

type docMetaVector struct {
	ID          string         `json:"id"`
	Description string         `json:"description"`
	Markdown    string         `json:"markdown"`
	Document    vault.Document `json:"document"`
	DocMeta     DocMeta        `json:"doc_meta"`
}

type retentionRulesFixture struct {
	SchemaVersion int               `json:"schema_version"`
	GeneratedOn   string            `json:"generated_on"`
	Oracle        RetentionOracle   `json:"oracle"`
	SourceHashes  map[string]string `json:"source_hashes"`
	LoadRules     []loadRulesVector `json:"load_rules"`
	DocMeta       []docMetaVector   `json:"doc_meta"`
	Notes         []string          `json:"notes"`
}

// TestPortRetentionRulesContract implements the port differential fixture system.
// Set PORT_GENERATE=1 to rewrite the fixture; a normal run verifies the
// checked-in fixture against the Go implementation. The fixture captures LoadRules
// and DocMetaFromDocument behavior for Go→Rust parity.
func TestPortRetentionRulesContract(t *testing.T) {
	fixture := buildRetentionRulesFixture(t)
	encoded, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	encoded = append(encoded, '\n')

	path := filepath.Join(portRepoRoot(t), retentionRulesFixturePath)
	if os.Getenv("PORT_GENERATE") == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			t.Fatal(err)
		}
		//nolint:gosec // fixture path is derived from the repository root
		if err := os.WriteFile(path, encoded, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", retentionRulesFixturePath, len(encoded))
		return
	}

	//nolint:gosec // fixture path is derived from the repository root
	current, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run with PORT_GENERATE=1 to create it)", retentionRulesFixturePath, err)
	}
	want, wantErr := retentionRulesPlatformDocument(current)
	got, gotErr := retentionRulesPlatformDocument(encoded)
	if wantErr != nil || gotErr != nil {
		t.Fatalf("normalise fixture for this platform: %v %v", wantErr, gotErr)
	}
	if string(want) != string(got) {
		t.Fatalf("retention rules fixture is stale; regenerate deliberately from the pinned Go oracle\n%s", retentionRulesVectorDifference(want, got))
	}
}

func buildRetentionRulesFixture(t *testing.T) retentionRulesFixture {
	return retentionRulesFixture{
		SchemaVersion: schemaVersion,
		GeneratedOn:   runtime.GOOS,
		Oracle:        RetentionOracle{Commit: sourceOracleCommit, Release: sourceOracleRelease},
		SourceHashes: map[string]string{
			"internal/retention/retention.go": retentionFileSHA256(t, "internal/retention/retention.go"),
			"internal/vault/vault.go":         retentionFileSHA256(t, "internal/vault/vault.go"),
		},
		LoadRules: loadRulesVectors(t),
		DocMeta:   docMetaVectors(t),
		Notes: []string{
			"Generated by internal/retention/port_retention_rules_contract_test.go; never hand-edit.",
			"LoadRules vectors exercise multi-document YAML files with --- separators.",
			"DocMetaFromDocument vectors use real vault.Document from the Go parser.",
		},
	}
}

func loadRulesVectors(t *testing.T) []loadRulesVector {
	var vectors []loadRulesVector

	// 1. Valid multi-rule file
	vectors = append(vectors, runLoadRulesCase(t, "valid-multi-rule", "valid multi-rule file", `name: "rule1"
period_days: 30
reference_field: document_date
action: trash
selector:
  document_type: invoice
---
name: "rule2"
period_days: 90
reference_field: created
action: flag_review
selector:
  status: paid
`))

	// 2. Valid single rule file
	vectors = append(vectors, runLoadRulesCase(t, "valid-single-rule", "valid single rule", `name: "single"
period_days: 7
reference_field: due_date
action: flag_review
`))

	// 3. Valid rule with default reference_field (empty -> document_date)
	vectors = append(vectors, runLoadRulesCase(t, "default-reference-field", "default reference field when empty", `name: "defaults"
period_days: 30
action: trash
`))

	// 4. # comment chunk (should be skipped)
	vectors = append(vectors, runLoadRulesCase(t, "comment-chunk", "comment chunk is skipped", `# This is a comment
---
name: "after-comment"
period_days: 10
action: trash
`))

	// 5. Empty chunk (should be skipped)
	vectors = append(vectors, runLoadRulesCase(t, "empty-chunk", "empty chunk is skipped", `---
name: "after-empty"
period_days: 5
action: flag_review
`))

	// 6. Missing name (validation error)
	vectors = append(vectors, runLoadRulesCase(t, "missing-name", "missing rule name fails validation", `name: "   "
period_days: 30
action: trash
`))

	// 7. Zero period_days (validation error)
	vectors = append(vectors, runLoadRulesCase(t, "zero-period", "zero period_days fails validation", `name: "zero"
period_days: 0
action: trash
`))

	// 8. Negative period_days (validation error)
	vectors = append(vectors, runLoadRulesCase(t, "negative-period", "negative period_days fails validation", `name: "negative"
period_days: -5
action: trash
`))

	// 9. Invalid reference_field
	vectors = append(vectors, runLoadRulesCase(t, "invalid-reference-field", "invalid reference_field fails validation", `name: "odd"
period_days: 30
reference_field: invoice_date
action: trash
`))

	// 10. Unknown YAML key (ignored by yaml.v3, rule still valid)
	vectors = append(vectors, runLoadRulesCase(t, "unknown-yaml-key", "unknown YAML key is ignored", `name: "unknown-key"
period_days: 30
action: trash
unknown_field: "ignored"
`))

	// 11. Malformed YAML
	vectors = append(vectors, runLoadRulesCase(t, "malformed-yaml", "malformed YAML fails parsing", `name: "broken"
period_days: 30
action: trash
  invalid_indent: true
`))

	// 12. CRLF line endings
	vectors = append(vectors, runLoadRulesCase(t, "crlf-endings", "CRLF line endings are handled", "name: \"crlf\"\r\nperiod_days: 30\r\naction: trash\r\n"))

	// 13. Empty file
	vectors = append(vectors, runLoadRulesCase(t, "empty-file", "empty file returns no rules", ""))

	// 14. Rule order preserved
	vectors = append(vectors, runLoadRulesCase(t, "rule-order", "rule order is preserved", `name: "first"
period_days: 10
action: trash
---
name: "second"
period_days: 20
action: flag_review
---
name: "third"
period_days: 30
action: trash
`))

	// 15. File not found
	vectors = append(vectors, loadRulesVector{
		ID:          "file-not-found",
		Description: "non-existent file returns read error",
		YAMLContent: "",
		Error:       "open /nonexistent/path/rules.yaml: no such file or directory",
		ErrorClass:  "read_failed",
	})

	return vectors
}

func runLoadRulesCase(t *testing.T, id, description, yamlContent string) loadRulesVector {
	dir := t.TempDir()
	path := filepath.Join(dir, "rules.yaml")
	//nolint:gosec // case file written into the test's own temp directory
	if err := os.WriteFile(path, []byte(yamlContent), 0o644); err != nil {
		t.Fatal(err)
	}
	rules, err := LoadRules(path)
	errorClass := ""
	errMsg := ""
	if err != nil {
		errMsg = err.Error()
		if strings.HasPrefix(errMsg, "open ") || strings.Contains(errMsg, "no such file") {
			errorClass = "read_failed"
		} else if strings.HasPrefix(errMsg, "parse retention rule:") {
			errorClass = "decode_failed"
		} else {
			errorClass = "validation"
		}
	}
	return loadRulesVector{
		ID:          id,
		Description: description,
		YAMLContent: yamlContent,
		Rules:       rules,
		Error:       errMsg,
		ErrorClass:  errorClass,
	}
}

func docMetaVectors(t *testing.T) []docMetaVector {
	var vectors []docMetaVector

	makeDoc := func(markdown string) *vault.Document {
		doc, err := vault.ParseBytes("test.md", []byte(markdown))
		if err != nil {
			t.Fatalf("ParseBytes failed: %v", err)
		}
		return doc
	}

	// 1. String correspondent and document_type
	doc1 := makeDoc(`---
title: "Test Doc"
correspondent: "Acme Corp"
document_type: invoice
---
Body content
`)
	meta1 := DocMetaFromDocument(doc1)
	vectors = append(vectors, docMetaVector{
		ID:          "string-correspondent-and-doctype",
		Description: "string correspondent and document_type extracted",
		Markdown: `---
title: "Test Doc"
correspondent: "Acme Corp"
document_type: invoice
---
Body content
`,
		Document: *doc1,
		DocMeta:  meta1,
	})

	// 2. Non-string correspondent (int) -> ""
	doc2 := makeDoc(`---
title: "Test Doc"
correspondent: 123
document_type: invoice
---
Body content
`)
	meta2 := DocMetaFromDocument(doc2)
	vectors = append(vectors, docMetaVector{
		ID:          "non-string-correspondent",
		Description: "non-string correspondent yields empty string",
		Markdown: `---
title: "Test Doc"
correspondent: 123
document_type: invoice
---
Body content
`,
		Document: *doc2,
		DocMeta:  meta2,
	})

	// 3. Non-string document_type (bool) -> ""
	doc3 := makeDoc(`---
title: "Test Doc"
correspondent: "Acme"
document_type: true
---
Body content
`)
	meta3 := DocMetaFromDocument(doc3)
	vectors = append(vectors, docMetaVector{
		ID:          "non-string-doctype",
		Description: "non-string document_type yields empty string",
		Markdown: `---
title: "Test Doc"
correspondent: "Acme"
document_type: true
---
Body content
`,
		Document: *doc3,
		DocMeta:  meta3,
	})

	// 4. Missing correspondent key -> ""
	doc4 := makeDoc(`---
title: "Test Doc"
document_type: invoice
---
Body content
`)
	meta4 := DocMetaFromDocument(doc4)
	vectors = append(vectors, docMetaVector{
		ID:          "missing-correspondent",
		Description: "missing correspondent key yields empty string",
		Markdown: `---
title: "Test Doc"
document_type: invoice
---
Body content
`,
		Document: *doc4,
		DocMeta:  meta4,
	})

	// 5. Missing document_type key -> ""
	doc5 := makeDoc(`---
title: "Test Doc"
correspondent: "Acme"
---
Body content
`)
	meta5 := DocMetaFromDocument(doc5)
	vectors = append(vectors, docMetaVector{
		ID:          "missing-doctype",
		Description: "missing document_type key yields empty string",
		Markdown: `---
title: "Test Doc"
correspondent: "Acme"
---
Body content
`,
		Document: *doc5,
		DocMeta:  meta5,
	})

	// 6. Nil tags -> empty slice
	doc6 := makeDoc(`---
title: "Test Doc"
---
Body content
`)
	meta6 := DocMetaFromDocument(doc6)
	vectors = append(vectors, docMetaVector{
		ID:          "nil-tags",
		Description: "nil tags becomes empty slice",
		Markdown: `---
title: "Test Doc"
---
Body content
`,
		Document: *doc6,
		DocMeta:  meta6,
	})

	// 7. Empty tags array -> empty slice
	doc7 := makeDoc(`---
title: "Test Doc"
tags: []
---
Body content
`)
	meta7 := DocMetaFromDocument(doc7)
	vectors = append(vectors, docMetaVector{
		ID:          "empty-tags",
		Description: "empty tags array becomes empty slice",
		Markdown: `---
title: "Test Doc"
tags: []
---
Body content
`,
		Document: *doc7,
		DocMeta:  meta7,
	})

	// 8. Unicode title
	doc8 := makeDoc(`---
title: "日本語タイトル"
correspondent: "山田太郎"
document_type: 文書
tags:
  - "タグ1"
  - "tag2"
---
Unicode body
`)
	meta8 := DocMetaFromDocument(doc8)
	vectors = append(vectors, docMetaVector{
		ID:          "unicode-title",
		Description: "unicode title and fields preserved",
		Markdown: `---
title: "日本語タイトル"
correspondent: "山田太郎"
document_type: 文書
tags:
  - "タグ1"
  - "tag2"
---
Unicode body
`,
		Document: *doc8,
		DocMeta:  meta8,
	})

	// 9. Non-string tags elements (mixed) -> strings kept, non-strings dropped
	doc9 := makeDoc(`---
title: "Test Doc"
tags: ["valid", 123, true, "also-valid"]
---
Body content
`)
	meta9 := DocMetaFromDocument(doc9)
	vectors = append(vectors, docMetaVector{
		ID:          "mixed-tags",
		Description: "non-string tag elements are dropped, strings kept",
		Markdown: `---
title: "Test Doc"
tags: ["valid", 123, true, "also-valid"]
---
Body content
`,
		Document: *doc9,
		DocMeta:  meta9,
	})

	// 10. All fields populated
	doc10 := makeDoc(`---
title: "Full Doc"
created: "2024-01-15T10:00:00Z"
document_date: "2024-01-15"
due_date: "2024-02-15"
status: "paid"
person: "Daniel"
correspondent: "Acme Corp"
document_type: invoice
tags:
  - "finance"
  - "2024"
---
Full body
`)
	meta10 := DocMetaFromDocument(doc10)
	vectors = append(vectors, docMetaVector{
		ID:          "all-fields",
		Description: "all DocMeta fields populated from Document",
		Markdown: `---
title: "Full Doc"
created: "2024-01-15T10:00:00Z"
document_date: "2024-01-15"
due_date: "2024-02-15"
status: "paid"
person: "Daniel"
correspondent: "Acme Corp"
document_type: invoice
tags:
  - "finance"
  - "2024"
---
Full body
`,
		Document: *doc10,
		DocMeta:  meta10,
	})

	return vectors
}

func retentionRulesPlatformDocument(document []byte) ([]byte, error) {
	var parsed retentionRulesFixture
	if err := json.Unmarshal(document, &parsed); err != nil {
		return nil, err
	}
	parsed.GeneratedOn = ""
	encoded, err := json.MarshalIndent(parsed, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

func retentionRulesVectorDifference(want, got []byte) string {
	var wantDoc, gotDoc map[string]json.RawMessage
	if err := json.Unmarshal(want, &wantDoc); err != nil {
		return err.Error()
	}
	if err := json.Unmarshal(got, &gotDoc); err != nil {
		return err.Error()
	}
	for _, section := range []string{"load_rules", "doc_meta"} {
		var wantItems, gotItems []map[string]any
		if err := json.Unmarshal(wantDoc[section], &wantItems); err != nil {
			return fmt.Sprintf("%s: %v", section, err)
		}
		if err := json.Unmarshal(gotDoc[section], &gotItems); err != nil {
			return fmt.Sprintf("%s: %v", section, err)
		}
		gotByID := make(map[string]any, len(gotItems))
		for _, item := range gotItems {
			gotByID[fmt.Sprint(item["id"])] = item
		}
		for _, item := range wantItems {
			id := fmt.Sprint(item["id"])
			counterpart, ok := gotByID[id]
			if !ok {
				return fmt.Sprintf("%s: fixture vector %q is missing from the generated document", section, id)
			}
			left, _ := json.Marshal(item)
			right, _ := json.Marshal(counterpart)
			if string(left) != string(right) {
				return fmt.Sprintf("%s: vector %q differs\n  fixture:   %s\n  generated: %s", section, id, left, right)
			}
		}
	}
	for _, section := range []string{"oracle", "source_hashes", "notes"} {
		if string(wantDoc[section]) != string(gotDoc[section]) {
			return fmt.Sprintf("%s differs\n  fixture:   %s\n  generated: %s", section, wantDoc[section], gotDoc[section])
		}
	}
	return "vectors are equal; the surrounding document differs"
}
